name: Accessibility Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}

      - name: Start server
        run: npm start &
        env:
          PORT: 3000

      - name: Wait for server
        run: |
          timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 2; done' || false

      - name: Run Pa11y CI
        uses: pa11y/pa11y-ci-action@v1
        with:
          urls: |
            http://localhost:3000
            http://localhost:3000/features
            http://localhost:3000/pricing
            http://localhost:3000/about
            http://localhost:3000/contact
          standard: WCAG2AA
          runners: ['htmlcs', 'axe']

      - name: Run WAVE
        uses: wave-accessibility/wave-action@v1
        with:
          url: 'http://localhost:3000'
          output: 'wave-results.json'

      - name: Upload accessibility results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: accessibility-results
          path: |
            pa11y-results/
            wave-results.json
          retention-days: 7 