name: Dependency Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Faithtech Marketing Website'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Run Retire.js
        uses: retirejs/retire.js-action@v1
        with:
          path: '.'
          output: 'reports/retirejs-report.json'
          severity: 'high'

      - name: Run Safety
        uses: pyupio/safety@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
          path: 'requirements.txt'

      - name: Run Bundler Audit
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Run Bundler Audit
        run: |
          gem install bundler-audit
          bundle-audit check --update

      - name: Run Composer Audit
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer

      - name: Run Composer Audit
        run: composer audit

      - name: Run Yarn Audit
        run: yarn audit

      - name: Run pnpm Audit
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Run pnpm Audit
        run: pnpm audit

      - name: Upload scan results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dependency-scan-results
          path: |
            reports/
            retirejs-report.json
          retention-days: 7 