name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run deploy
        run: npm run deploy

      - name: Run deploy:prod
        run: npm run deploy:prod

      - name: Run deploy:dev
        run: npm run deploy:dev

      - name: Run deploy:staging
        run: npm run deploy:staging

      - name: Run deploy:test
        run: npm run deploy:test

      - name: Run deploy:ci
        run: npm run deploy:ci

      - name: Run deploy:docker
        run: npm run deploy:docker

      - name: Run deploy:docker:prod
        run: npm run deploy:docker:prod

      - name: Run deploy:docker:dev
        run: npm run deploy:docker:dev

      - name: Run deploy:docker:staging
        run: npm run deploy:docker:staging

      - name: Run deploy:docker:test
        run: npm run deploy:docker:test

      - name: Run deploy:docker:ci
        run: npm run deploy:docker:ci

      - name: Run deploy:docker:push
        run: npm run deploy:docker:push

      - name: Run deploy:docker:push:prod
        run: npm run deploy:docker:push:prod

      - name: Run deploy:docker:push:dev
        run: npm run deploy:docker:push:dev

      - name: Run deploy:docker:push:staging
        run: npm run deploy:docker:push:staging

      - name: Run deploy:docker:push:test
        run: npm run deploy:docker:push:test

      - name: Run deploy:docker:push:ci
        run: npm run deploy:docker:push:ci

      - name: Run deploy:docker:push:latest
        run: npm run deploy:docker:push:latest

      - name: Run deploy:docker:push:latest:prod
        run: npm run deploy:docker:push:latest:prod

      - name: Run deploy:docker:push:latest:dev
        run: npm run deploy:docker:push:latest:dev

      - name: Run deploy:docker:push:latest:staging
        run: npm run deploy:docker:push:latest:staging

      - name: Run deploy:docker:push:latest:test
        run: npm run deploy:docker:push:latest:test

      - name: Run deploy:docker:push:latest:ci
        run: npm run deploy:docker:push:latest:ci

      - name: Run deploy:docker:push:latest:prod:dev
        run: npm run deploy:docker:push:latest:prod:dev

      - name: Run deploy:docker:push:latest:prod:staging
        run: npm run deploy:docker:push:latest:prod:staging

      - name: Run deploy:docker:push:latest:prod:test
        run: npm run deploy:docker:push:latest:prod:test

      - name: Run deploy:docker:push:latest:prod:ci
        run: npm run deploy:docker:push:latest:prod:ci

      - name: Run deploy:docker:push:latest:dev:staging
        run: npm run deploy:docker:push:latest:dev:staging

      - name: Run deploy:docker:push:latest:dev:test
        run: npm run deploy:docker:push:latest:dev:test

      - name: Run deploy:docker:push:latest:dev:ci
        run: npm run deploy:docker:push:latest:dev:ci

      - name: Run deploy:docker:push:latest:staging:test
        run: npm run deploy:docker:push:latest:staging:test

      - name: Run deploy:docker:push:latest:staging:ci
        run: npm run deploy:docker:push:latest:staging:ci

      - name: Run deploy:docker:push:latest:test:ci
        run: npm run deploy:docker:push:latest:test:ci

      - name: Run deploy:docker:push:latest:prod:dev:staging
        run: npm run deploy:docker:push:latest:prod:dev:staging

      - name: Run deploy:docker:push:latest:prod:dev:test
        run: npm run deploy:docker:push:latest:prod:dev:test

      - name: Run deploy:docker:push:latest:prod:dev:ci
        run: npm run deploy:docker:push:latest:prod:dev:ci

      - name: Run deploy:docker:push:latest:prod:staging:test
        run: npm run deploy:docker:push:latest:prod:staging:test

      - name: Run deploy:docker:push:latest:prod:staging:ci
        run: npm run deploy:docker:push:latest:prod:staging:ci

      - name: Run deploy:docker:push:latest:prod:test:ci
        run: npm run deploy:docker:push:latest:prod:test:ci

      - name: Run deploy:docker:push:latest:dev:staging:test
        run: npm run deploy:docker:push:latest:dev:staging:test

      - name: Run deploy:docker:push:latest:dev:staging:ci
        run: npm run deploy:docker:push:latest:dev:staging:ci

      - name: Run deploy:docker:push:latest:dev:test:ci
        run: npm run deploy:docker:push:latest:dev:test:ci

      - name: Run deploy:docker:push:latest:staging:test:ci
        run: npm run deploy:docker:push:latest:staging:test:ci

      - name: Run deploy:docker:push:latest:prod:dev:staging:test
        run: npm run deploy:docker:push:latest:prod:dev:staging:test

      - name: Run deploy:docker:push:latest:prod:dev:staging:ci
        run: npm run deploy:docker:push:latest:prod:dev:staging:ci

      - name: Run deploy:docker:push:latest:prod:dev:test:ci
        run: npm run deploy:docker:push:latest:prod:dev:test:ci

      - name: Run deploy:docker:push:latest:prod:staging:test:ci
        run: npm run deploy:docker:push:latest:prod:staging:test:ci

      - name: Run deploy:docker:push:latest:dev:staging:test:ci
        run: npm run deploy:docker:push:latest:dev:staging:test:ci

      - name: Run deploy:docker:push:latest:prod:dev:staging:test:ci
        run: npm run deploy:docker:push:latest:prod:dev:staging:test:ci

      - name: Upload deployment results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: deployment-results
          path: |
            dist/
            build/
            .next/
            out/
          retention-days: 7 