name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        uses: prettier/check@v1
        with:
          path: .

      - name: Run Stylelint
        uses: stylelint/action@v1
        with:
          path: .

      - name: Run TSLint
        uses: palantir/tslint-action@v1
        with:
          path: .

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '--ext .js,.jsx,.ts,.tsx'

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Run Pylint
        uses: PyCQA/pylint@master
        with:
          path: .
          output: reports/pylint-report.txt

      - name: Run Flake8
        uses: PyCQA/flake8@master
        with:
          path: .
          output: reports/flake8-report.txt

      - name: Run Black
        uses: psf/black@master
        with:
          path: .
          output: reports/black-report.txt

      - name: Run isort
        uses: pycqa/isort@master
        with:
          path: .
          output: reports/isort-report.txt

      - name: Run mypy
        uses: pre-commit/mirrors-mypy@master
        with:
          path: .
          output: reports/mypy-report.txt

      - name: Run Bandit
        uses: PyCQA/bandit@master
        with:
          targets: .
          format: json
          output: reports/bandit-report.json

      - name: Run ShellCheck
        uses: koalaman/shellcheck-action@master
        with:
          path: .

      - name: Run Markdownlint
        uses: DavidAnson/markdownlint-action@v1
        with:
          config: .markdownlint.json

      - name: Run HTMLHint
        uses: htmlhint/action@v1
        with:
          path: .

      - name: Run CSSLint
        uses: stylelint/action@v1
        with:
          path: .

      - name: Run JSONLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run YAMLLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run TOMLLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run INILint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run XMLlint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run CSVLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run HTMLLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run XMLLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run JSONLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run YAMLLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run TOMLLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run INILint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run XMLlint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run CSVLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run HTMLLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Run XMLLint
        uses: orhun/git-cliff-action@v1
        with:
          path: .

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-results
          path: |
            reports/
            .eslintcache
          retention-days: 7 